### ISSUE TITLE
problemos in el programmos

### ISSUE THREAD

**Issue by pasgoat** [Qumquat20/PIL-watermarker#1]
Progrrammme n0ot vv0Rklnj pR0p3rIy pl3z3 h3Ip I n33b 2 nnake moni
post-scriptum : i wuv u <333
![image_2021-11-30_224826](https://user-images.githubusercontent.com/95301041/144080249-9a64c8e3-0dd9-4988-9519-ecb75092da1a.png)
![image_2021-11-30_224849](https://user-images.githubusercontent.com/95301041/144080322-d3d2bf07-5aed-486e-8803-0e11942bd49a.png)

**Comment by ExoticWaffle** [comment]
MeEE T000 I habe samw iiShue, pLs heLP!!!!1!!! 

POST SKRIPPTOME (idk wahtw thE posSt is, Im sending The mesage via Internet), your Moms A kind man..
![lamy4](https://user-images.githubusercontent.com/63781036/144081268-2c0273be-97bf-47db-864c-0e3c3828d506.jpg)
![yukimaru1](https://user-images.githubusercontent.com/63781036/144081368-b0f4001e-bcda-4f49-b074-ed3ee25bec3c.jpg)
!

**Comment by Qumquat20** [comment]
??????????????????????????????????
